//! Core traits and types for the harness agent framework.
//!
//! This crate is intentionally tiny: it defines the data types that flow
//! through an agent ([`Message`], [`Content`]) and the two extension points
//! everything else plugs into — [`ChatModel`] (an LLM provider) and [`Tool`]
//! (something the model can call). It carries no HTTP client, no runtime and
//! no provider code, so implementing a new provider or tool only requires
//! depending on this crate.

mod error;
mod message;
mod model;
mod tool;

pub use error::{ModelError, ToolError};
pub use message::{Content, Message, Role};
pub use model::{
    ChatModel, ModelStream, Request, Response, StopReason, StreamEvent, ToolSpec, Usage,
};
pub use tool::{IntoToolOutput, Tool, ToolContext, ToolOutput};

pub use async_trait::async_trait;

/// Re-exports used by code generated by `harness-macros`. Not public API.
#[doc(hidden)]
pub mod __private {
    pub use schemars;
    pub use serde;
    pub use serde_json;
}

/// Collect tool values (typically unit structs generated by `#[tool]`) into
/// the `Vec<Arc<dyn Tool>>` that an agent expects.
///
/// ```ignore
/// let tools = tools![read_file, write_file, bash];
/// ```
#[macro_export]
macro_rules! tools {
    ($($t:expr),* $(,)?) => {
        vec![$(::std::sync::Arc::new($t) as ::std::sync::Arc<dyn $crate::Tool>),*]
    };
}
